export const CART_CONSTANTS = {
  FREE_DELIVERY_THRESHOLD: 500,
  CASHBACK_THRESHOLD: 1000,
  CASHBACK_PERCENTAGE: 1,
  DEFAULT_DELIVERY_FEE: 50,
  PLATFORM_FEE: 10,
  MAX_RECOMMENDED_PRODUCTS: 3,
} as const;

